version: '3.8'

services:
  transaction-service:
    image: 'transaction-service-microservice'
    build:
      context: .
    container_name: transaction-service
    depends_on:
      - postgres-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-container:5432/transaction_service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - "8000:8555"

  postgres-container:
    image: postgres
    container_name: postgres-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=transaction_service
    ports:
      - "5432"